version: "3.8"
services:
  jenkins:
    image: jenkins/jenkins:jdk21
    environment:
      - ANDROID_SDK_ROOT=/var/jenkins_home/android/sdk/
# run stuff below on start    
# chmod 666 /var/run/docker.sock
# docker exec -it -u root jenkins-test-jenkins-1 /bin/bash
# apt install python3 python3-pip python3.11-venv
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/trivy:/usr/bin/trivy
      # install android sdk to folowing dir
      - /home/metacringer/Android/Sdk:/var/jenkins_home/android/sdk/

  registry:
    image: registry:latest
    ports:
      - "5000:5000"
    volumes:
      - registry-data:/var/lib/registry
  artifactory:
    image: releases-docker.jfrog.io/jfrog/artifactory-oss:latest
    ports:
      - "8082:8082"
      - "8081:8081"
    volumes:
      - artifactory-data:/var/opt/jfrog/artifactory
  mobsf:
    image: opensecurity/mobile-security-framework-mobsf:latest
    ports:
      - "8000:8000"
volumes:
  artifactory-data:
  jenkins-home:
  registry-data:
